### ISSUE TITLE
Can't change api key.

### ISSUE THREAD

**Issue by shaunthasheep** [VDSoft/TheTVDBApi#1]
Just a suggestion: the api key should be changeable. I know it's easy to change in the code but not if you install by nuget. Also great job on the wrapper

**Comment by ChristophvdF** [comment]
Hi shaunthasheep 
I am planing on changing the webinterface in slight ways (providing a real interface) with this change I will also change the handling of the api key, like providing it with the instance of the webinterfaces constructor or similar

**Comment by ChristophvdF** [comment]
With the new version an api key is mandatory.
