### ISSUE TITLE
Request: set custom path for ZIP and extraction

### ISSUE THREAD

**Issue by DanCooper** [VDSoft/TheTVDBApi#8]
HI
is there any way to set the path for file downloading? I don't like it that the files are dwonloaded to the main folder and not the temp folder that we used for all things like this.

**Comment by ChristophvdF** [comment]
Hi,
this is already implemented but not published in the nuget pack if you loaded it over nuget. I'm currently working on some changed which will be published as nuget soon.

To use the feature pls load the current source and integrate it into your solution.
To set the download path see:

``` csharp
/// <summary>
/// Initializes a new instance of the <see cref="WebInterface"/> class.
/// </summary>
/// <param name="apiKey">API key obtained from TheTVDB.com to access the XML api.</param>
/// <param name="fileDirectory">Directory where all loaded files will be stored.</param>
public WebInterface(string apiKey, string fileDirectory)
{
        this.APIKey = apiKey;
        this.FileDirectory = fileDirectory;
}
```

In WebInterface.cs

**Comment by DanCooper** [comment]
Hi,
thank you!

**Comment by ChristophvdF** [comment]
You're welcome. You're the second one to test this feature so please report back if you have any problems with it I really would appreciate.

**Comment by ChristophvdF** [comment]
Fixed in the newest version.
Available at https://www.nuget.org/packages/TheTVDBApi
